# fly.toml app configuration file generated for bold-bird-4760 on 2023-06-02T05:24:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-bird-4760"
primary_region = "lhr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
